Scrum.Web/Controllers/AutenticacaoController.cs
using Scrum.Dominio.Models;
using Scrum.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Scrum.Web.Controllers
{
    public class AutenticacaoController : Controller
    {
        private ScrumWebContext db = new ScrumWebContext();
        // GET: Autenticacao
        public ActionResult Login()
        {
            //ViewBag.ReturnUrl = returnUrl;
            return View();
        }
        [HttpPost]
        public ActionResult Login(Usuario usuario, string returnUrl)
        {
            Usuario user = db.Usuario.FirstOrDefault(u => u.email == usuario.email);

            if (Equals(usuario.email, "") || Equals(usuario.email, null))
            {
               Response.Write("<script>alert('Informe o usuario.');</script>");
            }
            else if (Equals(usuario.senha, "") || Equals(usuario.senha, null))
            {
               Response.Write("<script>alert('Informe a Senha.');</script>");
            }
            else
            {
                //if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/") && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                //{
                    FormsAuthentication.SetAuthCookie(user.email, false);
                    Sessoes.LogarUser(user);
                    ViewBag.UsuarioLogado = user.nome;
                    return Redirect("/Home");
                //}


            }
            return View(new Usuario());
        }
        public ActionResult Cadastro()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Cadastro(Usuario usuario)
        {
            usuario.dataCriacao = DateTime.Now;
            if (usuario.senha == usuario.senha)
            {
                if (ModelState.IsValid)
                {
                    db.Usuario.Add(usuario);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Login");
                }
            }
            return View(usuario);
        }
        [HttpPost]
        public ActionResult Sair()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");

        }
    }
}

Scrum.Web/Views/Autenticacao/Cadastro.cshtml
@model Scrum.Dominio.Models.Usuario
@{
    ViewBag.Title = "Cadastro - Scrum";
    Layout = "~/Views/Shared/_Login.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal panel panel-default col-sm-7 col-md-5 col-md-offset-4">
        <div class="panel-heading text-center"> <strong>Cadastro ScrumFac</strong></div>
        <div class="panel-body">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-sm-10 col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.senha, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-sm-10 col-md-10">
                    @Html.EditorFor(model => model.senha, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.senha, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.confirmaSenha, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-sm-10 col-md-10">
                    @Html.EditorFor(model => model.confirmaSenha, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.confirmaSenha, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-sm-10 col-md-10">
                    @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
                </div>
            </div>
            @*<div class="form-group">
                    @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-sm-10 col-md-10">
                        @Html.EditorFor(model => model.foto, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.foto, "", new { @class = "text-danger" })
                    </div>
                </div>*@
            @*<div class="form-group">
                <div class="col-sm-12 col-md-12">
                    <input type="file" class="btn btn-warning" id="FotoUpload" />
                </div>
                </div>*@
            <div class="form-group text-center">
                <div class="col-md-10 col-sm-10">
                    <input type="submit" value="Cadastrar" class="btn btn-success" />
                </div>
            </div>
        </div>
        <div class="panel-footer text-right">
            @Html.ActionLink("Voltar", "Login", "Autenticacao")
        </div>

    </div>
}


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/methods_pt.js"></script>

Scrum.Web/Views/Autenticacao/Login.cshtml
@model Scrum.Dominio.Models.Usuario

@{
    ViewBag.Title = "Login - Scrum";
    Layout = "~/Views/Shared/_Login.cshtml";
}

<div class="container" style="margin-top: 40px">
    <div class="row">

        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <div class="panel panel-default">

                <div class="panel-heading"> <strong> Scrum Login</strong></div>
                <div class="panel-body">

                    @using (Html.BeginForm("Login", "Autenticacao", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-signin" }))
                    {
                        <fieldset>
                            <div class="row">
                                <div class="center-block">
                                    <img class="profile-img" src="" alt="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-10  col-md-offset-1 ">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="glyphicon glyphicon-user"> </i>
                                            </span>
                                            @Html.TextBoxFor(model => model.email, new { @class = "form-control", placeholder = "Informe seu login" })                                           
                                        </div>
                                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="glyphicon glyphicon-lock"> </i>
                                            </span>
                                            @Html.PasswordFor(model => model.senha, new { @class = "form-control", placeholder = "Informe sua seha" })
                                            
                                        </div>
                                        @Html.ValidationMessageFor(model => model.senha, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" class="btn btn-lg btn-primary btn-block" value="Acessar">
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    }

                </div>
                <div class="panel-footer text-right">
                   @Html.ActionLink("Registre-se", "Cadastro", "Autenticacao")
                </div>
            </div>
        </div>
    </div>
</div>